version: 2
jobs:
  build:
    docker:
      - image: - image: docker:17.09.0-ce-git
    steps:
      - checkout
      - build_remote_docker

      - run:
        name: Build docker image
        command: |
          - docker build --rm=false -t mcfio/mumble-server .

      - run:
        name: Test image
        command: |
          - docker run -d -p 64738:64738 mcfio/mumble-server; sleep 10
          - curl --retry 10 --retry-delay 5 -v http://localhost:64738

      - run:
        name: Push Docker image
        command: |
          - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
          - docker push mcfio/mumble-server
