version: 2
jobs:
  build:
    docker:
      - image: docker:17.09.0-ce-git
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Install dependencies
          command: |
            apk add --no-cache curl

      - run:
          name: Build docker image
          command: |
            docker build -f Dockerfile -t mcfio-mumble-server .

      - run:
          name: Test image
          command: |
            docker run -d -p 64738:64738 mcfio-mumble-server; sleep 10
            curl --retry 10 --retry-delay 5 -v http://localhost:64738
