version: 2
jobs:
  build:
    docker:
      - image: docker:17.09.0-ce-git
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Install dependencies
          command: |
            apk add --no-cache curl

      - run:
          name: Build docker image
          command: |
            docker build -f Dockerfile -t mcfio-mumble-server .
