machine:
  services:
    - docker

dependencies:
  override:
    - docker info
    - docker build --rm=false -t mcfio/mumble-server .

test:
  override:
    - docker run -d -p 64738:64738 mcfio/mumble-server; sleep 10
    - curl --retry 10 --retry-delay 5 -v http://localhost:64738

deployment:
  hub:
    branch: master
    commands:
      - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
      - docker push mcfio/mumble-server
