version: 2
jobs:
  build:
    docker:
      - image: docker:17.09.0-ce-git
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build docker image
          command: |
            docker build -f Dockerfile \
              --build-arg VCS_REF=`git rev-parse --short HEAD` \
              --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
              -t mcfio-mumble-server .

      - run:
          name: Push image to Docker Hub
          command: |
            docker login -u $DOCKER_USER --password-stdin $DOCKER_PASS
            docker tag mcfio-mumble-server mcfio/mumble-server:latest
            docker push mcfio/mumble-server:latest
