#!/usr/bin/with-contenv bash

# copy default murmur.ini if one does not exist
[[ ! -f /config/mumble-server.ini ]] && cp /defaults/murmur.ini /config/mumble-server.ini

# permissions
chown -R mcf:mcf \
	/config
